/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GiaoDien;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javafx.scene.layout.Background;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author DELL
 */
public class JF_MenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form JF_MenuAdmin
     */
    public JF_MenuAdmin() {
        initComponents();
        loadtennv();
    }
    private void loadtennv(){
        String id = Code.DangNhap.idnv;
        String sql = "SELECT tennv FROM nhanvien WHERE manv = ?";
        try (
            Connection con = Code.DataBaseHelper.openConnection();
            PreparedStatement stmt = con.prepareStatement(sql);
        ) {
            
            stmt.setString(1, id);
            ResultSet rs = stmt.executeQuery();

            if (rs.next()) {
                txtTenNV.setText(rs.getString("tennv"));
            } else {
              txtTenNV.setText("");
            }
        } catch (Exception e) {
            System.out.println("Kết nối không thành công");
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Có lỗi xảy ra: " + e.getMessage());

        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnNen = new javax.swing.JPanel();
        jpNen = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jpQldg = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jpqls = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jpqlnv = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jpTK = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jpmuon = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jpus = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jpdx = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jpdkm = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jpesc = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtTenNV = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jptra1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Thư Viện");

        pnNen.setBackground(java.awt.Color.white);
        pnNen.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnNenMouseMoved(evt);
            }
        });

        jpNen.setBackground(new java.awt.Color(255, 255, 255));
        jpNen.setForeground(new java.awt.Color(255, 255, 255));
        jpNen.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpNenMouseMoved(evt);
            }
        });

        jpQldg.setBackground(new java.awt.Color(204, 204, 255));
        jpQldg.setPreferredSize(new java.awt.Dimension(250, 48));
        jpQldg.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnQlgdMouseMoved(evt);
            }
        });
        jpQldg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnQlgdMousePressed(evt);
            }
        });

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(12, 18, 34));
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/users-alt.png"))); // NOI18N
        jLabel24.setText("Quản lí đọc giả");

        javax.swing.GroupLayout jpQldgLayout = new javax.swing.GroupLayout(jpQldg);
        jpQldg.setLayout(jpQldgLayout);
        jpQldgLayout.setHorizontalGroup(
            jpQldgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpQldgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jpQldgLayout.setVerticalGroup(
            jpQldgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpQldgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpqls.setBackground(new java.awt.Color(204, 204, 255));
        jpqls.setPreferredSize(new java.awt.Dimension(250, 48));
        jpqls.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpqlsbtnQlgdMouseMoved(evt);
            }
        });
        jpqls.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btSachMousePressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(12, 18, 34));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/books.png"))); // NOI18N
        jLabel12.setText("Quản lí sách");

        javax.swing.GroupLayout jpqlsLayout = new javax.swing.GroupLayout(jpqls);
        jpqls.setLayout(jpqlsLayout);
        jpqlsLayout.setHorizontalGroup(
            jpqlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpqlsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jpqlsLayout.setVerticalGroup(
            jpqlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpqlsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpqlnv.setBackground(new java.awt.Color(204, 204, 255));
        jpqlnv.setPreferredSize(new java.awt.Dimension(250, 48));
        jpqlnv.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpqlnvbtnQlgdMouseMoved(evt);
            }
        });
        jpqlnv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btNhanvienMousePressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(12, 18, 34));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/users (1).png"))); // NOI18N
        jLabel10.setText("Quản lý tài khoản");

        javax.swing.GroupLayout jpqlnvLayout = new javax.swing.GroupLayout(jpqlnv);
        jpqlnv.setLayout(jpqlnvLayout);
        jpqlnvLayout.setHorizontalGroup(
            jpqlnvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpqlnvLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jpqlnvLayout.setVerticalGroup(
            jpqlnvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpqlnvLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpTK.setBackground(new java.awt.Color(204, 204, 255));
        jpTK.setPreferredSize(new java.awt.Dimension(250, 48));
        jpTK.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpTKMouseMoved(evt);
            }
        });
        jpTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btTKMousePressed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(12, 18, 34));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/thongke_1.png"))); // NOI18N
        jLabel17.setText("Thống kế");
        jLabel17.setPreferredSize(new java.awt.Dimension(139, 29));
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btTKMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jpTKLayout = new javax.swing.GroupLayout(jpTK);
        jpTK.setLayout(jpTKLayout);
        jpTKLayout.setHorizontalGroup(
            jpTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTKLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jpTKLayout.setVerticalGroup(
            jpTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTKLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpmuon.setBackground(new java.awt.Color(204, 204, 255));
        jpmuon.setPreferredSize(new java.awt.Dimension(250, 48));
        jpmuon.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpmuonbtnQlgdMouseMoved(evt);
            }
        });
        jpmuon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btMuonSachMousePressed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(12, 18, 34));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/muon.png"))); // NOI18N
        jLabel14.setText("Mượn sách");
        jLabel14.setPreferredSize(new java.awt.Dimension(139, 29));

        javax.swing.GroupLayout jpmuonLayout = new javax.swing.GroupLayout(jpmuon);
        jpmuon.setLayout(jpmuonLayout);
        jpmuonLayout.setHorizontalGroup(
            jpmuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpmuonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jpmuonLayout.setVerticalGroup(
            jpmuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpmuonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpus.setBackground(new java.awt.Color(204, 204, 255));
        jpus.setPreferredSize(new java.awt.Dimension(250, 48));
        jpus.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpusbtnQlgdMouseMoved(evt);
            }
        });
        jpus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btAboutUsMousePressed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(12, 18, 34));
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/customer-service (1).png"))); // NOI18N
        jLabel28.setText("About US");

        javax.swing.GroupLayout jpusLayout = new javax.swing.GroupLayout(jpus);
        jpus.setLayout(jpusLayout);
        jpusLayout.setHorizontalGroup(
            jpusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jpusLayout.setVerticalGroup(
            jpusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpdx.setBackground(new java.awt.Color(204, 204, 255));
        jpdx.setPreferredSize(new java.awt.Dimension(250, 48));
        jpdx.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpdxbtnQlgdMouseMoved(evt);
            }
        });
        jpdx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btLogoutMousePressed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(12, 18, 34));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Thoat_1.png"))); // NOI18N
        jLabel22.setText("Logout");

        javax.swing.GroupLayout jpdxLayout = new javax.swing.GroupLayout(jpdx);
        jpdx.setLayout(jpdxLayout);
        jpdxLayout.setHorizontalGroup(
            jpdxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpdxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jpdxLayout.setVerticalGroup(
            jpdxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpdxLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addContainerGap())
        );

        jpdkm.setBackground(new java.awt.Color(204, 204, 255));
        jpdkm.setPreferredSize(new java.awt.Dimension(250, 48));
        jpdkm.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpdkmbtnQlgdMouseMoved(evt);
            }
        });
        jpdkm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btDoimatkhauMousePressed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(12, 18, 34));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/key.png"))); // NOI18N
        jLabel23.setText("Đổi mật khẩu");

        javax.swing.GroupLayout jpdkmLayout = new javax.swing.GroupLayout(jpdkm);
        jpdkm.setLayout(jpdkmLayout);
        jpdkmLayout.setHorizontalGroup(
            jpdkmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpdkmLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jpdkmLayout.setVerticalGroup(
            jpdkmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpdkmLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addContainerGap())
        );

        jpesc.setBackground(new java.awt.Color(204, 204, 255));
        jpesc.setPreferredSize(new java.awt.Dimension(250, 48));
        jpesc.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpescbtnQlgdMouseMoved(evt);
            }
        });
        jpesc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btExitMousePressed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 73, 73));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/thoat (2).png"))); // NOI18N
        jLabel20.setText("Thoát");

        javax.swing.GroupLayout jpescLayout = new javax.swing.GroupLayout(jpesc);
        jpesc.setLayout(jpescLayout);
        jpescLayout.setHorizontalGroup(
            jpescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpescLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jpescLayout.setVerticalGroup(
            jpescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpescLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/User.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Admin");

        txtTenNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTenNV.setText("Phạm Yến Nhi");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/menu (1).png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 34)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/mainmenu (3).png"))); // NOI18N
        jLabel5.setText("Quản lý thư viện");

        jptra1.setBackground(new java.awt.Color(204, 204, 255));
        jptra1.setPreferredSize(new java.awt.Dimension(250, 48));
        jptra1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jptra1MouseMoved(evt);
            }
        });
        jptra1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jptra1btTraSachMousePressed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(12, 18, 34));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/tra.png"))); // NOI18N
        jLabel18.setText(" Trả sách");
        jLabel18.setPreferredSize(new java.awt.Dimension(139, 29));
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel18btTraSachMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jptra1Layout = new javax.swing.GroupLayout(jptra1);
        jptra1.setLayout(jptra1Layout);
        jptra1Layout.setHorizontalGroup(
            jptra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jptra1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jptra1Layout.setVerticalGroup(
            jptra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jptra1Layout.createSequentialGroup()
                .addGroup(jptra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jptra1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jptra1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpNenLayout = new javax.swing.GroupLayout(jpNen);
        jpNen.setLayout(jpNenLayout);
        jpNenLayout.setHorizontalGroup(
            jpNenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNenLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jpdx, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jpesc, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpNenLayout.createSequentialGroup()
                .addGroup(jpNenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpNenLayout.createSequentialGroup()
                        .addGroup(jpNenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpNenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jpqlnv, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jpmuon, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jpTK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jpdkm, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jpQldg, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jpqls, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jpus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jptra1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 82, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpNenLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jpNenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpNenLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpNenLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jpNenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtTenNV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpNenLayout.setVerticalGroup(
            jpNenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpNenLayout.createSequentialGroup()
                .addGroup(jpNenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpNenLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpNenLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jpNenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpNenLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTenNV)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(jpQldg, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jpqls, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jpqlnv, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jpmuon, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jptra1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jpdkm, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jpus, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jpNenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpesc, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpdx, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpTK, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnNenLayout = new javax.swing.GroupLayout(pnNen);
        pnNen.setLayout(pnNenLayout);
        pnNenLayout.setHorizontalGroup(
            pnNenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpNen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnNenLayout.setVerticalGroup(
            pnNenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnNenLayout.createSequentialGroup()
                .addComponent(jpNen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnNen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnNen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btNhanvienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btNhanvienMousePressed
        // TODO add your handling code here:
        JF_QLNhanVien l = new JF_QLNhanVien();
        l.setVisible(true);
        l.setLocationRelativeTo(null);
//        this.dispose();
    }//GEN-LAST:event_btNhanvienMousePressed

    private void btSachMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSachMousePressed
        JF_QLSach s = new JF_QLSach();
        s.setVisible(true);
        s.setLocationRelativeTo(null);
//        this.dispose();
    }//GEN-LAST:event_btSachMousePressed

    private void btMuonSachMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btMuonSachMousePressed
        JF_MuonSach ms = new JF_MuonSach();

        ms.setVisible(true);
        ms.setLocationRelativeTo(null);
//        this.dispose();
    }//GEN-LAST:event_btMuonSachMousePressed

    private void btTKMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btTKMousePressed
        JF_ThongKe ts = new JF_ThongKe();
        ts.setVisible(true);
        ts.setLocationRelativeTo(null);
//        this.dispose();
    }//GEN-LAST:event_btTKMousePressed

    private void btAboutUsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAboutUsMousePressed
        JF_AboutUs a = new JF_AboutUs();
        a.setVisible(true);
        a.setLocationRelativeTo(null);
    }//GEN-LAST:event_btAboutUsMousePressed

    private void btLogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLogoutMousePressed
        JF_DangNhap l = new JF_DangNhap();
        l.setVisible(true);
        l.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btLogoutMousePressed

    private void btExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExitMousePressed
        System.exit(0);
    }//GEN-LAST:event_btExitMousePressed

    private void pnNenMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnNenMouseMoved
        
    }//GEN-LAST:event_pnNenMouseMoved

    private void btDoimatkhauMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDoimatkhauMousePressed
        // TODO add your handling code here:
        JF_DoiMatKhau s = new JF_DoiMatKhau();
        s.setVisible(true);
        s.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_btDoimatkhauMousePressed

    private void btnQlgdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQlgdMousePressed
//        // TODO add your handling code here:
            JF_QLDocGia s = new JF_QLDocGia();
            s.setVisible(true);
            s.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnQlgdMousePressed

    private void jpNenMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpNenMouseMoved
        // TODO add your handling code here:
        resetColor(jpQldg);
        resetColor(jpdkm);
        resetColor(jpdx);
        resetColor(jpmuon);
        resetColor(jpTK); 
        resetColor(jpesc);
        resetColor(jpus);
        resetColor(jpqlnv);
        resetColor(jpqls);        
        resetColor(jptra1);

    }//GEN-LAST:event_jpNenMouseMoved

    private void jpqlsbtnQlgdMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpqlsbtnQlgdMouseMoved
        // TODO add your handling code here:
                    setColor(jpqls);

        
    }//GEN-LAST:event_jpqlsbtnQlgdMouseMoved

    private void jpqlnvbtnQlgdMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpqlnvbtnQlgdMouseMoved
        // TODO add your handling code here:
        setColor(jpqlnv);
    }//GEN-LAST:event_jpqlnvbtnQlgdMouseMoved

    private void jpmuonbtnQlgdMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpmuonbtnQlgdMouseMoved
        // TODO add your handling code here:
        setColor(jpmuon);
    }//GEN-LAST:event_jpmuonbtnQlgdMouseMoved

    private void jpTKMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpTKMouseMoved
        // TODO add your handling code here:
        setColor(jpTK);
    }//GEN-LAST:event_jpTKMouseMoved

    private void jpusbtnQlgdMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpusbtnQlgdMouseMoved
        // TODO add your handling code here:
        setColor(jpus);
    }//GEN-LAST:event_jpusbtnQlgdMouseMoved

    private void jpdxbtnQlgdMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpdxbtnQlgdMouseMoved
        // TODO add your handling code here:
        setColor(jpdx);
    }//GEN-LAST:event_jpdxbtnQlgdMouseMoved

    private void jpdkmbtnQlgdMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpdkmbtnQlgdMouseMoved
        // TODO add your handling code here:
        setColor(jpdkm);
    }//GEN-LAST:event_jpdkmbtnQlgdMouseMoved

    private void jpescbtnQlgdMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpescbtnQlgdMouseMoved
        // TODO add your handling code here:
        setColor(jpesc);
    }//GEN-LAST:event_jpescbtnQlgdMouseMoved

    private void btnQlgdMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQlgdMouseMoved
        // TODO add your handling code here:
        setColor(jpQldg);
    }//GEN-LAST:event_btnQlgdMouseMoved

    private void jpTSMouseMoved(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
        setColor(jptra1);
    }    
    private void jLabel18btTraSachMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18btTraSachMousePressed
        // TODO add your handling code here:
            JF_TraSach s = new JF_TraSach();
            s.setVisible(true);
            s.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_jLabel18btTraSachMousePressed

    private void jptra1btTraSachMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jptra1btTraSachMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jptra1btTraSachMousePressed

    private void jptra1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jptra1MouseMoved
        // TODO add your handling code here:
        setColor(jptra1);
    }//GEN-LAST:event_jptra1MouseMoved
    
    void resetColor(JPanel pn){
        pn.setBackground(new Color(255,255,255));
    }
    
    void setColor(JPanel pn){
            pn.setBackground(new Color(218,218,218));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_MenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jpNen;
    private javax.swing.JPanel jpQldg;
    private javax.swing.JPanel jpTK;
    private javax.swing.JPanel jpdkm;
    private javax.swing.JPanel jpdx;
    private javax.swing.JPanel jpesc;
    private javax.swing.JPanel jpmuon;
    private javax.swing.JPanel jpqlnv;
    private javax.swing.JPanel jpqls;
    private javax.swing.JPanel jptra1;
    private javax.swing.JPanel jpus;
    private javax.swing.JPanel pnNen;
    private javax.swing.JLabel txtTenNV;
    // End of variables declaration//GEN-END:variables
}
